name: Installer Builder

on:
  push:
    branches:
      - installer-script
  pull_request:
    branches:
      - installer-script

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10' 
    - run: |
        python -m pip install nuitka
        python -m nuitka installer.py --standalone --onefile
          
